#include "stdafx.h"
#include "CHANGE_BUTTON_STATE_IND.hpp"


CHANGE_BUTTON_STATE_IND::CHANGE_BUTTON_STATE_IND()
{
	name = "CHANGE_BUTTON_STATE_IND";
}


CHANGE_BUTTON_STATE_IND::~CHANGE_BUTTON_STATE_IND()
{
}
