#include "stdafx.h"
#include "CHANGE_CONNECTOR_DONE_IND.hpp"


CHANGE_CONNECTOR_DONE_IND::CHANGE_CONNECTOR_DONE_IND()
{
	name = "CHANGE_CONNECTOR_DONE_IND";
}


CHANGE_CONNECTOR_DONE_IND::~CHANGE_CONNECTOR_DONE_IND()
{
}
