#include "stdafx.h"
#include "CONNECTORS_MASKING_DONE_IND.hpp"


CONNECTORS_MASKING_DONE_IND::CONNECTORS_MASKING_DONE_IND()
{
	name = "CONNECTORS_MASKING_DONE_IND";
}


CONNECTORS_MASKING_DONE_IND::~CONNECTORS_MASKING_DONE_IND()
{
}
