#include "stdafx.h"
#include "LIGHT_WELCOMING_TASK.h"


LIGHT_WELCOMING_TASK::LIGHT_WELCOMING_TASK()
{
	this->name = EName::LIGHT_WELCOMING_TASK;
}


LIGHT_WELCOMING_TASK::~LIGHT_WELCOMING_TASK()
{
}
