#include "stdafx.h"
#include "LIGHT_GOODBYE_TASK.h"


LIGHT_GOODBYE_TASK::LIGHT_GOODBYE_TASK()
{
	this->name = MODULE_TASK::EName::LIGHT_GOODBYE_TASK;
}


LIGHT_GOODBYE_TASK::~LIGHT_GOODBYE_TASK()
{
}
