#include "stdafx.h"
#include "MASK_CONNECTORS_STATE.hpp"


MASK_CONNECTORS_STATE::MASK_CONNECTORS_STATE()
{
	type = EName::MASK_CONNECTORS_STATE;
}


MASK_CONNECTORS_STATE::~MASK_CONNECTORS_STATE()
{
}
